$(document).ready(function(){
    $(".image1").hover(function(){
        $(".text1").toggle();
    });
    $(".image2").hover(function(){
        $(".text2").toggle();
    });
    $(".image3").hover(function(){
        $(".text3").toggle(); 
    });
    $(".image4").hover(function(){
        $(".text4").toggle(); 
    });
    $(".image5").hover(function(){
        $(".text5").toggle(); 
    });
    $(".image6").hover(function(){
        $(".text6").toggle(); 
    });
    $(".image7").hover(function(){
        $(".text7").toggle(); 
    });
    $(".image8").hover(function(){
        $(".text8").toggle(); 
    });
    $(".image9").hover(function(){
        $(".text9").toggle(); 
    });
    $(".image10").hover(function(){
        $(".text10").toggle(); 
    });
    $(".image11").hover(function(){
        $(".text11").toggle(); 
    });
    $(".image12").hover(function(){
        $(".text12").toggle(); 
    });
    $(".image13").hover(function(){
        $(".text13").toggle(); 
    });
    $(".image14").hover(function(){
        $(".text14").toggle(); 
    });
});